name: GoVet

on:
  pull_request:
    branches: [ "main" ]

jobs:
  vet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: vet
        run: go vet --all ./...
